version: '3.7'

services:
  backend:
    build: ./backend
    command: node ./src/index.js
    #volumes:
    #  - ./backend:/usr/src/backend 
    ports: 
      - "9000:9000"
  frontend:
    build: ./frontend
    ports: 
      - "8000:8000"
    depends_on: 
      - backend